[SAT-78] Criar aplicação de demonstração do SAT em Delphi
controlid/integracao pull request #15
Opened 2022-05-03 14:38 UTC by thiagorodrigues-controlid

Adição de exemplo em Delphi para SAT.

**Tarefa:** [SAT-78: Criar aplicação de demonstração do SAT em Delphi](https://controlid.atlassian.net/browse/SAT-78)

**Implementação:**

- SAT-78: master - controlid/integracao

**Dependência:**

- Nenhuma

2022-05-03 23:37 UTC, albert-controlid commented
Olá, Thiago, tudo bem? Ficou muito bom mas gostaria de algumas mudanças:
1) Especificar no README o link do SDK do SAT para download e explicar qual versão da DLL tem q usar 32 bit STDCALL ou CDECL.
2) Incluir a DLL da versão atual na pasta para o cara já conseguir testar de cara, sem precisar baixar nada.

2022-07-12 03:25 UTC, andrecurvello-controlid requested changes
@thiagorodrigues-controlid, pode subir esse exemplo com a DLL mais recente, já da última homologação?

E mais, consegue adicionar telas da aplicação no README.md?

2022-07-19 19:07 UTC, andrecurvello-controlid requested changes

2022-07-19 19:07 UTC, andrecurvello-controlid commented on Automação Comercial/SAT - Delphi/LEIAME.md
> +O exemplo implementa as funções ExtraisLogs, ConsultarStatusOperacioinal, TesteFimaFim, ConsultarSat e EnviarDadosVenda. Para o funcionamento correto, insira o __código de ativação__ do equipamento n
ExtraisLogs -> ExtrairLogs

2022-07-19 19:07 UTC, andrecurvello-controlid commented on Automação Comercial/SAT - Delphi/LEIAME.md
> +Para verificar o exemplo de enviar dados de uma venda, insira o nome do arquivo que contém o _CFe_ de venda e pressione o botão adequado para carregar.
Onde esse arquivo tem que estar localizado? No mesmo diretório que o executável?

2022-07-19 19:07 UTC, andrecurvello-controlid commented on Automação Comercial/SAT - Delphi/LEIAME.md
> +O retorno de cada função é exibido em uma mensagem.
Essa mensagem aparece em uma nova caixa de diálogo?

2022-07-19 19:37 UTC, merged